### ISSUE TITLE
Implement difficulty levels

### ISSUE THREAD

**Issue by puppe1990** [puppe1990/speed-type-code-words#2]
## Implement difficulty levels
Currently, the app does not allow users to select different difficulty levels for the text they are typing. This feature would be useful for users to practice typing at different levels and improve their skills.

## Proposed solution
* Add a dropdown menu to the UI where users can select the difficulty level.
* Add different texts for each difficulty level in the app's data
* Show the selected text to the user based on their selection
## To-do List
- [ ] Add a dropdown menu to the UI
- [ ] Add different texts for each difficulty level in the app's data
- [ ] Show the selected text to the user based on their selection
- [ ] Add a default option for the difficulty level
- [ ] Add tooltips to indicate the difficulty level of the texts
## Additional considerations
* The difficulty levels should be clearly labeled and easy to understand for the user.
* The texts for each difficulty level should be appropriate for that level.

## Acceptance criteria
* The users can select the difficulty level from a dropdown menu
* The app shows the selected text based on the user's selection
* The difficulty levels are clearly labeled and easy to understand for the user
* The texts for each difficulty level are appropriate for that level
